### ISSUE TITLE
Specify font

### ISSUE THREAD

**Issue by stereoit** [xhtml2pdf/django-xhtml2pdf#12]
Hello,
 how would I specify the font? I've managed to put the page into PDF, but a lot of characters are not displayed correctly, I guess this is related to font character set?

**Comment by luisza** [comment]
Please see https://xhtml2pdf.readthedocs.io/en/latest/reference.html?highlight=font#fonts

```
@font-face {
  font-family: Example, "Example Font";
  src: url(example.ttf);
}
```
